fixed config

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -42,6 +42,13 @@ jobs:
         if: github.event_name == 'push'
         run: ./gradlew clean test --parallel --info --stacktrace
 
+      - name: Debug cucumber file
+        run: |
+          echo "---- BUILD CONTENT ----"
+          ls -la build/
+          echo "---- CUCUMBER JSON ----"
+          cat build/cucumber-report.json || echo "FILE NOT FOUND"  
+
       - name: Import Gherkin scenarios to Xray
         if: github.event_name == 'push'
         run: |
@@ -62,17 +69,20 @@ jobs:
             -H "Content-Type: application/json" \
             -d "{\"client_id\":\"${{ secrets.XRAY_CLIENT_ID }}\",\"client_secret\":\"${{ secrets.XRAY_CLIENT_SECRET }}\"}" | tr -d '"')
 
-          echo '{
+          cat <<EOF > test-exec.json
+          {
             "info": {
               "summary": "Automation Execution",
               "description": "Execution from GitHub Actions",
               "project": "E2E"
             }
-          }' > test-exec.json
+          }
+          EOF
 
           curl -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart" \
             -H "Authorization: Bearer $TOKEN" \
             -F "info=@test-exec.json" \  
+            -F "results=build/cucumber-report.json"
 
       - name: Load previous Allure history
         uses: actions/checkout@v4
